// Códigos estáveis para cada mensagem de erro de negócio. O `message` no corpo
// da resposta continua em pt-BR (compatibilidade com clientes/testes existentes);
// o `code` permite que o frontend traduza a mensagem para o idioma ativo do usuário
// em vez de exibir o texto pt-BR vindo da API. Ver jiujitsu-frontend/messages/*/apiErrors.json.
export const ErrorCodes = {
  // Academias
  ACADEMIA_NOT_FOUND: 'ACADEMIA_NOT_FOUND',
  ACADEMIA_ACCESS_DENIED: 'ACADEMIA_ACCESS_DENIED',
  CNPJ_ALREADY_EXISTS: 'CNPJ_ALREADY_EXISTS',
  ACADEMIA_HAS_LINKED_RECORDS: 'ACADEMIA_HAS_LINKED_RECORDS',

  // Alunos
  ALUNO_NOT_FOUND: 'ALUNO_NOT_FOUND',
  ALUNO_HAS_LINKED_RECORDS: 'ALUNO_HAS_LINKED_RECORDS',
  ALUNO_ALREADY_HAS_ACTIVE_MATRICULA: 'ALUNO_ALREADY_HAS_ACTIVE_MATRICULA',
  ALUNO_NO_ACTIVE_MATRICULA: 'ALUNO_NO_ACTIVE_MATRICULA',
  ALUNO_ALREADY_LINKED_TO_PROFESSOR: 'ALUNO_ALREADY_LINKED_TO_PROFESSOR',

  // Campos únicos (compartilhado entre módulos de cadastro)
  CPF_ALREADY_EXISTS: 'CPF_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // Professores
  PROFESSOR_NOT_FOUND: 'PROFESSOR_NOT_FOUND',
  PROFESSOR_NOT_LINKED_TO_ACADEMIA: 'PROFESSOR_NOT_LINKED_TO_ACADEMIA',
  PROFESSOR_ALREADY_LINKED_TO_ACADEMIA: 'PROFESSOR_ALREADY_LINKED_TO_ACADEMIA',
  PROFESSOR_HAS_LINKED_AULAS: 'PROFESSOR_HAS_LINKED_AULAS',
  PROFESSOR_SUBSTITUTE_SAME_AS_TITULAR: 'PROFESSOR_SUBSTITUTE_SAME_AS_TITULAR',
  PROFESSOR_SUBSTITUTE_NOT_FOUND: 'PROFESSOR_SUBSTITUTE_NOT_FOUND',
  VINCULO_NOT_FOUND: 'VINCULO_NOT_FOUND',

  // Aulas
  AULA_NOT_FOUND: 'AULA_NOT_FOUND',
  AULA_TEMPLATE_NOT_FOUND: 'AULA_TEMPLATE_NOT_FOUND',
  AULA_TEMPLATE_NONE_ACTIVE: 'AULA_TEMPLATE_NONE_ACTIVE',
  AULA_CANNOT_EDIT_FINISHED: 'AULA_CANNOT_EDIT_FINISHED',
  AULA_HAS_PRESENCAS: 'AULA_HAS_PRESENCAS',
  AULA_CANNOT_CANCEL_FINISHED: 'AULA_CANNOT_CANCEL_FINISHED',
  AULA_ONLY_SCHEDULED_CAN_START: 'AULA_ONLY_SCHEDULED_CAN_START',
  AULA_ONLY_IN_PROGRESS_CAN_COMPLETE: 'AULA_ONLY_IN_PROGRESS_CAN_COMPLETE',
  AULA_CANNOT_CHANGE_PROFESSOR_FINISHED: 'AULA_CANNOT_CHANGE_PROFESSOR_FINISHED',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_USER_INVALID_OR_INACTIVE: 'AUTH_USER_INVALID_OR_INACTIVE',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_TOKEN_NOT_PROVIDED: 'AUTH_TOKEN_NOT_PROVIDED',
  AUTH_TOKEN_INVALID_FORMAT: 'AUTH_TOKEN_INVALID_FORMAT',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_NOT_AUTHENTICATED: 'AUTH_NOT_AUTHENTICATED',
  AUTH_FORBIDDEN_RESOURCE: 'AUTH_FORBIDDEN_RESOURCE',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  AUTH_ONLY_ADMIN_CAN_CREATE_ADMIN: 'AUTH_ONLY_ADMIN_CAN_CREATE_ADMIN',
  AUTH_ONLY_ADMIN_CAN_CREATE_RECEPCIONISTA: 'AUTH_ONLY_ADMIN_CAN_CREATE_RECEPCIONISTA',
  AUTH_RECEPCIONISTA_CANNOT_CREATE_PROFESSOR: 'AUTH_RECEPCIONISTA_CANNOT_CREATE_PROFESSOR',
  AUTH_CANNOT_CREATE_USER_OTHER_ACADEMIA: 'AUTH_CANNOT_CREATE_USER_OTHER_ACADEMIA',

  // Cadastro público
  CADASTRO_PUBLICO_NOT_FOUND: 'CADASTRO_PUBLICO_NOT_FOUND',
  CADASTRO_PUBLICO_PENDING_EXISTS: 'CADASTRO_PUBLICO_PENDING_EXISTS',
  CADASTRO_PUBLICO_ALREADY_REGISTERED: 'CADASTRO_PUBLICO_ALREADY_REGISTERED',
  CADASTRO_PUBLICO_ALREADY_PROCESSED: 'CADASTRO_PUBLICO_ALREADY_PROCESSED',
  CADASTRO_PUBLICO_EMAIL_ALREADY_EXISTS: 'CADASTRO_PUBLICO_EMAIL_ALREADY_EXISTS',
  CADASTRO_PUBLICO_CPF_ALREADY_EXISTS: 'CADASTRO_PUBLICO_CPF_ALREADY_EXISTS',
  CADASTRO_PUBLICO_PROFESSOR_NOT_FOUND: 'CADASTRO_PUBLICO_PROFESSOR_NOT_FOUND',

  // Financeiro
  PLANO_NOT_FOUND: 'PLANO_NOT_FOUND',
  PLANO_HAS_LINKED_MATRICULAS: 'PLANO_HAS_LINKED_MATRICULAS',
  MATRICULA_NOT_FOUND: 'MATRICULA_NOT_FOUND',
  MATRICULA_ALREADY_CANCELLED: 'MATRICULA_ALREADY_CANCELLED',
  MENSALIDADE_NOT_FOUND: 'MENSALIDADE_NOT_FOUND',
  MENSALIDADE_SOME_NOT_FOUND: 'MENSALIDADE_SOME_NOT_FOUND',
  MENSALIDADE_MUST_BE_SAME_ACADEMIA: 'MENSALIDADE_MUST_BE_SAME_ACADEMIA',
  MENSALIDADE_SOME_ALREADY_PAID: 'MENSALIDADE_SOME_ALREADY_PAID',

  // Graduações
  GRADUACAO_NOT_FOUND: 'GRADUACAO_NOT_FOUND',
  GRADUACAO_CANNOT_DOWNGRADE_FAIXA: 'GRADUACAO_CANNOT_DOWNGRADE_FAIXA',
  GRADUACAO_CANNOT_DOWNGRADE_GRAU: 'GRADUACAO_CANNOT_DOWNGRADE_GRAU',
  GRADUACAO_MAX_GRAUS_EXCEEDED: 'GRADUACAO_MAX_GRAUS_EXCEEDED',

  // Presenças
  PRESENCA_NOT_FOUND: 'PRESENCA_NOT_FOUND',
  PRESENCA_ONLY_IN_PROGRESS_OR_COMPLETED: 'PRESENCA_ONLY_IN_PROGRESS_OR_COMPLETED',
  PRESENCA_ALREADY_REGISTERED: 'PRESENCA_ALREADY_REGISTERED',
  PRESENCA_CANNOT_REMOVE_FINISHED_AULA: 'PRESENCA_CANNOT_REMOVE_FINISHED_AULA',

  // Reservas
  RESERVA_NOT_FOUND: 'RESERVA_NOT_FOUND',
  RESERVA_CANNOT_BOOK_CANCELLED_AULA: 'RESERVA_CANNOT_BOOK_CANCELLED_AULA',
  RESERVA_CANNOT_BOOK_PAST_AULA: 'RESERVA_CANNOT_BOOK_PAST_AULA',
  RESERVA_CAN_ONLY_CREATE_FOR_SELF: 'RESERVA_CAN_ONLY_CREATE_FOR_SELF',
  RESERVA_FALTAS_LIMIT_REACHED: 'RESERVA_FALTAS_LIMIT_REACHED',
  RESERVA_ALREADY_EXISTS: 'RESERVA_ALREADY_EXISTS',
  RESERVA_CANNOT_CANCEL_OTHERS: 'RESERVA_CANNOT_CANCEL_OTHERS',
  RESERVA_ALREADY_CANCELLED: 'RESERVA_ALREADY_CANCELLED',
  RESERVA_CANNOT_CANCEL_PAST_AULA: 'RESERVA_CANNOT_CANCEL_PAST_AULA',
  RESERVA_ONLY_WAITING_CAN_CONFIRM: 'RESERVA_ONLY_WAITING_CAN_CONFIRM',

  // Validação (Zod) — ver validation.middleware.ts
  VALIDATION_ERROR_BODY: 'VALIDATION_ERROR_BODY',
  VALIDATION_ERROR_QUERY: 'VALIDATION_ERROR_QUERY',
  VALIDATION_ERROR_PARAMS: 'VALIDATION_ERROR_PARAMS',

  // Rate limiting — ver rate-limit.middleware.ts
  RATE_LIMIT_GENERAL: 'RATE_LIMIT_GENERAL',
  RATE_LIMIT_LOGIN: 'RATE_LIMIT_LOGIN',
  RATE_LIMIT_CREATE: 'RATE_LIMIT_CREATE',

  // Erros genéricos (Prisma / infraestrutura) — ver error-handler.middleware.ts
  DUPLICATE_FIELD: 'DUPLICATE_FIELD',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  RELATED_RECORD_NOT_FOUND: 'RELATED_RECORD_NOT_FOUND',
  REQUIRED_RELATION_MISSING: 'REQUIRED_RELATION_MISSING',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INVALID_OPERATION_DATA: 'INVALID_OPERATION_DATA',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
